---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: dhl-go2-bpms-demo-my-project
      name: dhl-go2-bpms-demo-my-project
      namespace: dhl-go2-bpms
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: dhl-go2-bpms-demo-my-project
      template:
        metadata:
          labels:
            app: dhl-go2-bpms-demo-my-project
        spec:
          securityContext:
            runAsUser: 0
          containers:
          - image: registry-144fd7c1.nip.io/v2/wm1015bpm:v1
            imagePullPolicy: Always
            livenessProbe:
              failureThreshold: 60
              httpGet:
                path: /invoke/wm.server/ping
                port: 5555
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 5
            name: dhl-go2-bpms-demo-my-project
            ports:
            - containerPort: 5555
              protocol: TCP
            - containerPort: 9999
              protocol: TCP
            - containerPort: 5543
              protocol: TCP
            - containerPort: 9202
              protocol: TCP
            volumeMounts:
            - name: application-properties
              mountPath: /opt/softwareag/IntegrationServer/application.properties
              subPath: application.properties
            - name: taskclient-properties
              mountPath: /opt/softwareag/IntegrationServer/instances/default/packages/WmTaskClient/config/taskclient.properties
              subPath: taskclient.properties
            - name: license-file
              mountPath: /opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml
              subPath: licenseKey.xml
              defaultMode: 0777
            readinessProbe:
              failureThreshold: 60
              httpGet:
                path: /invoke/wm.server/ping
                port: 5555
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 5
          imagePullSecrets:
          - name: sag-dhl-go2-registry-secret    
          volumes:
          - name: prtcnf
            configMap:
              name: dhl-go2-bpms-demo-my-project-configmap-prt-settings
              items:
              - key: prt.cnf
                path: prt.cnf   
          - name: custom-wrapper-conf
            configMap:
              name: dhl-go2-bpms-demo-my-project-custom-wrapper-conf
              items:
              - key: custom_wrapper.conf
                path: custom_wrapper.conf
          - name: jdbc-pool-conf
            configMap:
              name: dhl-go2-bpms-demo-my-project-jdbc-pool-xml
              items:
              - key: wm_db.xml
                path: wm_db.xml
          - name: application-properties
            configMap:
              name: dhl-go2-bpms-demo-my-project-application-properties
              items:
              - key: application.properties
                path: application.properties
          - name: license-file
            configMap:
              name: dhl-go2-bpms-demo-my-project-license-key
              defaultMode: 0777
              items:
              - key: licenseKey.xml
                path: licenseKey.xml
          - name: taskclient-properties
            configMap:
              name: dhl-go2-bpms-demo-my-project-taskclient-properties
              items:
              - key: taskclient.properties
                path: taskclient.properties
