---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: dhl-go2-bpms-demo-my-project
      name: dhl-go2-bpms-demo-my-project
      namespace: dhl-go2-bpms
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: dhl-go2-bpms-demo-my-project
      template:
        metadata:
          labels:
            app: dhl-go2-bpms-demo-my-project
        spec:
          securityContext:
            runAsUser: 0
          containers:
          - image: registry-144fd7c1.nip.io/v2/dhl-go2-bpmspoc-is-image:v1.0
            imagePullPolicy: Always
            livenessProbe:
              failureThreshold: 60
              httpGet:
                path: /invoke/wm.server/ping
                port: 5555
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 5
            name: dhl-go2-bpms-demo-my-project
            ports:
            - containerPort: 5555
              protocol: TCP
            - containerPort: 9999
              protocol: TCP
            - containerPort: 5543
              protocol: TCP
            - containerPort: 9202
              protocol: TCP
            volumeMounts:
            - name: application-properties
              mountPath: /opt/softwareag/IntegrationServer/application.properties
              subPath: application.properties
            - name: taskclient-properties
              mountPath: /opt/softwareag/IntegrationServer/instances/default/packages/WmTaskClient/config/taskclient.properties
              subPath: taskclient.properties
            - name: license-file
              mountPath: /opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml
              subPath: licenseKey.xml
            - name: jms-cnf
              mountPath: /opt/softwareag/IntegrationServer/instances/default/config/jms.cnf
              subPath: jms.cnf
            - name: custom-wrapper-conf
              mountPath: /opt/softwareag/profiles/IS_default/configuration/custom_wrapper.conf
              subPath: custom_wrapper.conf
            - name: taskengine-properties
              mountPath: /opt/softwareag/profiles/IS_default/configuration/com.softwareag.platform.config.propsloader/com.softwareag.catalina.connector.https.pid-TaskEngine.properties
              subPath: com.softwareag.catalina.connector.https.pid-TaskEngine.properties
            readinessProbe:
              failureThreshold: 60
              httpGet:
                path: /invoke/wm.server/ping
                port: 5555
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 5
          imagePullSecrets:
          - name: sag-dhl-go2-registry-secret    
          volumes:
          - name: application-properties
            configMap:
              name: dhl-go2-bpms-demo-my-project-application-properties
              items:
              - key: application.properties
                path: application.properties
          - name: license-file
            configMap:
              name: dhl-go2-bpms-demo-my-project-license-key
              defaultMode: 0777
              items:
              - key: licenseKey.xml
                path: licenseKey.xml
          - name: jms-cnf
            configMap:
              name: dhl-go2-bpms-demo-my-project-jms-cnf
              defaultMode: 0777
              items:
              - key: jms.cnf
                path: jms.cnf
          - name: taskclient-properties
            configMap:
              name: dhl-go2-bpms-demo-my-project-taskclient-properties
              items:
              - key: taskclient.properties
                path: taskclient.properties
          - name: custom-wrapper-conf
            configMap:
              name: dhl-go2-bpms-demo-my-project-custom-wrapper-conf
              items:
              - key: custom_wrapper.conf
                path: custom_wrapper.conf
          - name: taskengine-properties
            configMap:
              name: dhl-go2-bpms-demo-my-project-taskengine-properties
              items:
              - key: com.softwareag.catalina.connector.https.pid-TaskEngine.properties
                path: com.softwareag.catalina.connector.https.pid-TaskEngine.properties
