kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dhl-go2-bpms-demo-um-data-0-pvc
  namespace: dhl-go2-bpms
  annotations:
    volume.beta.kubernetes.io/storage-class: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi